spring:
  datasource:
    url: jdbc:h2:mem:certificates;DB_CLOSE_DELAY=-1
    username: username
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database: h2
  flyway:
    url: jdbc:h2:mem:certificates;DB_CLOSE_DELAY=-1
    user: username
    password: password
    driver-class-name: org.h2.Driver
    baseline-on-migrate: true
    locations: classpath:db/migration/dev