CREATE TABLE gift_certificate
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY DEFAULT ON NULL,
    name        VARCHAR(255)                            NOT NULL,
    description VARCHAR(255)                            NOT NULL,
    price       DECIMAL                                 NOT NULL,
    duration    BIGINT                                  NOT NULL,
    create_date TIMESTAMP WITH TIME ZONE                NOT NULL,
    update_date TIMESTAMP WITH TIME ZONE                NOT NULL,
    status      VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_gift_certificate PRIMARY KEY (id)
);

CREATE TABLE gift_tag
(
    gift_id BIGINT NOT NULL,
    tag_id  BIGINT NOT NULL,
    CONSTRAINT pk_gift_tag PRIMARY KEY (gift_id, tag_id)
);

CREATE TABLE tag
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY DEFAULT ON NULL,
    name   VARCHAR(255)                            NOT NULL,
    status VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_tag PRIMARY KEY (id)
);

ALTER TABLE tag
    ADD CONSTRAINT uc_tag_name UNIQUE (name);

ALTER TABLE gift_certificate
    ADD CONSTRAINT uc_gift_certificate_name UNIQUE (name);

ALTER TABLE gift_tag
    ADD CONSTRAINT fk_gift_tag_on_gift_certificate FOREIGN KEY (gift_id) REFERENCES gift_certificate (id);

ALTER TABLE gift_tag
    ADD CONSTRAINT fk_gift_tag_on_tag FOREIGN KEY (tag_id) REFERENCES tag (id);